export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';

export const FAVE_IMAGE = 'App/FAVE_IMAGE';
export const UNFAVE_IMAGE = 'App/UNFAVE_IMAGE';
export const FETCH_IMAGES = 'App/FETCH_IMAGES';
export const RECEIVE_IMAGES = 'App/RECEIVE_IMAGES';

export const ADD_IMAGE_FORM = 'App/Forms/ADD_IMAGE_FORM';

export const PREVIEW_IMAGE_RECEIVED = 'App/PREVIEW_IMAGE_RECEIVED';
export const PREVIEW_IMAGE_RECEIVING = 'App/PREVIEW_IMAGE_RECEIVING';

export const SUBMIT_IMAGE_PENDING = 'App/SUBMIT_IMAGE_PENDING';
export const SUBMIT_IMAGE_FINISH = 'App/SUBMIT_IMAGE_FINISH';

export const RESET_ERROR_MESSAGE = 'App/RESET_ERROR_MESSAGE';

export const SAVE_GUEST_TOKEN = 'App/SAVE_GUEST_TOKEN';
